config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  get '/technologies', to: 'technologies#index'
  get '/projects', to: 'projects#index'
  get '/pricing', to: 'pricing#index'
  get '/about', to: 'about#index'

  resources :payments

  post '/set_locale', to: 'application#set_locale'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    # Retrieve the user's preferred language from the request
    user_lang = params[:locale] || request.headers['Accept-Language'] || I18n.default_locale

    # You can implement logic here to map browser language codes to your supported languages
    # For simplicity, let's assume you have a mapping in your application configuration
    available_locales = Rails.application.config.i18n.available_locales
    lang_code = available_locales.include?(user_lang.to_sym) ? user_lang.to_sym : I18n.default_locale

    # Set the locale for the current request
    I18n.locale = lang_code
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new; end

  def create
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: 500,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path
  end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index; end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  def index; end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<div class="about-container">
  <div class="about-content">
    <div class="about-image-wrapper">
      <div class="about-img-top"></div>
    </div>

    <div>
      <h2>About Erick Contreras</h2>

      <div class="about-description">
        <p>
          Erick started writing code since 2019 at collegue when he was studying Electrical and Electronic Engineering.
          He has been fall in love with coding since then and make him lead his life through Software.
        </p>

        <p>
          He has built web apps and websites for business' large and small. He has been working with different teams through 
          his career finding interesting challenges and waiting for new ones that can
          lead him to learn new ways to tackle problems.
        </p>

        <p>
          On his spread time he loves to develop executable CLI applications
          to automate some of his tasks in the daily basis, enjoy motoGP in sundays and sometimes sing a song before sunset.
        </p>
      </div>
    </div>

    <div class="about-img"></div>
  </div>
</div>

app/views/curriculum/index.html.erb
<main>
  <section class="section-content">
    <div class="polygon"></div>
    <div class="outer">
      <div class="container">

        <h1>Curriculm page</h1>
      </div>
    </div>
  </section>
</main>

app/views/home/index.html.erb
<div class="row">
  <div class="col1">
    <div class="bgimage-col-wrapper">
      <div class="bgimage-col1"></div>
    </div>
    <h4>Types of Custom Software Developement</h4>
    <div class="home-ul-wrapper">
      <ul>
        <li>Customized Product Development</li>
        <li>Mobile App Development</li>
        <li>Ecommerce Software Development</li>
        <li>Software as a Service Development</li>
        <li>Content Management System</li>
        <li>Customer Relationship Management System</li>
        <li>Enterprise Resource Planning Software</li>
        <li>Operation Management System</li>
        <li>Enterprise Software Solutions</li>
        <li>Fintech Software Development</li>
      </ul>
    </div>
  </div>

  <div class="col2">
    <div class="bgimage-col-wrapper">
      <div class="bgimage-col2"></div>
    </div>
    <h4>Just SOME of the things you will get</h4>
    <div class="home-ul-wrapper">
      <ul>
        <li>Business-oriented</li>
        <li>Client Retention</li>
        <li>Reliability</li>
        <li>Scalability</li>
        <li>Integration</li>
        <li>Security</li>
        <li>Cost-Effective</li>
        <li>Business Automation</li>
        <li>Integratable with other systems</li>
        <li>Maintainable for longevity</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Welcome! | Erick's Website</title>
  <meta
    name="viewport"
    content="height=device-height,
    width=device-width,
    initial-scale=1.0,
    minimum-scale=1.0,
    maximum-scale=1.0,
    user-scalable=no,
    target-densitydpi=device-dpi"
  >
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%#= javascript_include_tag "turbo" %>
  <!--  <meta name="turbo-prefetch" content="false">-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.7/axios.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap">
</head>

<body>
<!--<div class="imagebg"></div>-->
<video id="myVideo" playsinline autoplay muted loop>
  <source src="<%= ENV['S3_BUCKET_VIDEO'] %>" type="video/mp4">
</video>

<header id="<%= current_page?(root_path) ? 'site-header' : 'site-header-other-paths' %>">
  <!-- Hamburger button -->
  <button id="hamburger-menu">
    <div class="hamburger-menu-line"></div>
    <div class="hamburger-menu-line"></div>
    <div class="hamburger-menu-line"></div>
  </button>

  <!-- Mobile menu or modal -->
  <div id="modal">
    <div id="modal-x">X</div>
    <div class="modal-content">
      <ul>
        <li><%= link_to 'Home', root_path, class: ('active' if current_page?(root_path)) %></li>
        <li><%= link_to 'Technologies', technologies_path, class: ('active' if current_page?(technologies_path)) %></li>
        <!-- <li><%= link_to 'Projects' %></li> -->
        <!-- <li><%= link_to 'Pricing', pricing_path, class: ('active' if current_page?(pricing_path)) %></li> -->
        <li><%= link_to 'About', about_path, class: ('active' if current_page?(about_path)) %></li>
      </ul>
    </div>

    <div class="buttons modal-buttons">
      <a class="btn-left modal-buttons-btn-left" href="https://calendly.com/er-contreras" target="_blank">
        ☎ Book a
        <u>Free</u>
        Consultation
      </a>
      <a class="btn-right modal-buttons-btn-left" href="mailto:er.contreras@hotmail.com">Email me</a>
    </div>
  </div>

  <!-- Desktop menu -->
  <div class="full-container">
    <div class="buttons">
      <a class="btn-left" href="https://calendly.com/er-contreras" target="_blank">
        ☎ Book a
        <u>Free</u>
        Consultation
      </a>
      <a class="btn-right" href="mailto:er.contreras@hotmail.com">Email me</a>
    </div>

    <ul>
      <li><%= link_to 'Home', root_path, class: ('active' if current_page?(root_path)) %></li>
      <li><%= link_to 'Technologies', technologies_path, class: ('active' if current_page?(technologies_path)) %></li>
      <!-- <li><%= link_to 'Projects' %></li> -->
      <!-- <li><%= link_to 'Pricing', pricing_path, class: ('active' if current_page?(pricing_path)) %></li> -->
      <li><%= link_to 'About', about_path, class: ('active' if current_page?(about_path)) %></li>
    </ul>
  </div>

  <div class="container">
    <div class="name-header">
      <a>
        <h3 id="change-color">
          Erick Contreras
          <span style="font-size: 1rem">Software Developer</span>
        </h3>
        <% if current_page?(projects_path) %>
          <span style="color: yellow; border: 2px solid orange; padding: 0.6rem; margin-top: 2rem; font-size: 2rem;">Under Construction! 👷‍️💻🚧</span>
        <% end %>
      </a>

      <% if current_page?(root_path) %>
        <h1 style="margin-top: 2rem;">
          Order your custom software today!
        </h1>
      <% end %>
    </div>
  </div>
</header>

<main>
  <div class="polygon"></div>

  <section class="section-content">
    <div class="outer">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </section>
</main>

<footer>
  <div class="rights-reserved">
    <p>Order your custom software today!</p>
    <br>
    <p>Copyright © 2024 Erick Contreras | All Rights Reserved</p>
  </div>

  <div class="social-media">
    <a href="https://www.linkedin.com/in/er-contreras/" target="_blank" class="fa fa-linkedin">
      <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0 0 48 48">
        <path fill="#0288D1" d="M42,37c0,2.762-2.238,5-5,5H11c-2.761,0-5-2.238-5-5V11c0-2.762,2.239-5,5-5h26c2.762,0,5,2.238,5,5V37z"></path>
        <path fill="#FFF" d="M12 19H17V36H12zM14.485 17h-.028C12.965 17 12 15.888 12 14.499 12 13.08 12.995 12 14.514 12c1.521 0 2.458 1.08 2.486 2.499C17 15.887 16.035 17 14.485 17zM36 36h-5v-9.099c0-2.198-1.225-3.698-3.192-3.698-1.501 0-2.313 1.012-2.707 1.99C24.957 25.543 25 26.511 25 27v9h-5V19h5v2.616C25.721 20.5 26.85 19 29.738 19c3.578 0 6.261 2.25 6.261 7.274L36 36 36 36z"></path>
      </svg>
    </a>
    <a href="https://twitter.com/er_contreras_" target="_blank" class="fa fa-twitter">
      <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0 0 48 48">
        <path fill="#03A9F4" d="M42,12.429c-1.323,0.586-2.746,0.977-4.247,1.162c1.526-0.906,2.7-2.351,3.251-4.058c-1.428,0.837-3.01,1.452-4.693,1.776C34.967,9.884,33.05,9,30.926,9c-4.08,0-7.387,3.278-7.387,7.32c0,0.572,0.067,1.129,0.193,1.67c-6.138-0.308-11.582-3.226-15.224-7.654c-0.64,1.082-1,2.349-1,3.686c0,2.541,1.301,4.778,3.285,6.096c-1.211-0.037-2.351-0.374-3.349-0.914c0,0.022,0,0.055,0,0.086c0,3.551,2.547,6.508,5.923,7.181c-0.617,0.169-1.269,0.263-1.941,0.263c-0.477,0-0.942-0.054-1.392-0.135c0.94,2.902,3.667,5.023,6.898,5.086c-2.528,1.96-5.712,3.134-9.174,3.134c-0.598,0-1.183-0.034-1.761-0.104C9.268,36.786,13.152,38,17.321,38c13.585,0,21.017-11.156,21.017-20.834c0-0.317-0.01-0.633-0.025-0.945C39.763,15.197,41.013,13.905,42,12.429"></path>
      </svg>
    </a>
    <a href="https://github.com/er-contreras" target="_blank" class="fa fa-github">
      <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0 0 50 50">
        <path d="M17.791,46.836C18.502,46.53,19,45.823,19,45v-5.4c0-0.197,0.016-0.402,0.041-0.61C19.027,38.994,19.014,38.997,19,39 c0,0-3,0-3.6,0c-1.5,0-2.8-0.6-3.4-1.8c-0.7-1.3-1-3.5-2.8-4.7C8.9,32.3,9.1,32,9.7,32c0.6,0.1,1.9,0.9,2.7,2c0.9,1.1,1.8,2,3.4,2 c2.487,0,3.82-0.125,4.622-0.555C21.356,34.056,22.649,33,24,33v-0.025c-5.668-0.182-9.289-2.066-10.975-4.975 c-3.665,0.042-6.856,0.405-8.677,0.707c-0.058-0.327-0.108-0.656-0.151-0.987c1.797-0.296,4.843-0.647,8.345-0.714 c-0.112-0.276-0.209-0.559-0.291-0.849c-3.511-0.178-6.541-0.039-8.187,0.097c-0.02-0.332-0.047-0.663-0.051-0.999 c1.649-0.135,4.597-0.27,8.018-0.111c-0.079-0.5-0.13-1.011-0.13-1.543c0-1.7,0.6-3.5,1.7-5c-0.5-1.7-1.2-5.3,0.2-6.6 c2.7,0,4.6,1.3,5.5,2.1C21,13.4,22.9,13,25,13s4,0.4,5.6,1.1c0.9-0.8,2.8-2.1,5.5-2.1c1.5,1.4,0.7,5,0.2,6.6c1.1,1.5,1.7,3.2,1.6,5 c0,0.484-0.045,0.951-0.11,1.409c3.499-0.172,6.527-0.034,8.204,0.102c-0.002,0.337-0.033,0.666-0.051,0.999 c-1.671-0.138-4.775-0.28-8.359-0.089c-0.089,0.336-0.197,0.663-0.325,0.98c3.546,0.046,6.665,0.389,8.548,0.689 c-0.043,0.332-0.093,0.661-0.151,0.987c-1.912-0.306-5.171-0.664-8.879-0.682C35.112,30.873,31.557,32.75,26,32.969V33 c2.6,0,5,3.9,5,6.6V45c0,0.823,0.498,1.53,1.209,1.836C41.37,43.804,48,35.164,48,25C48,12.318,37.683,2,25,2S2,12.318,2,25 C2,35.164,8.63,43.804,17.791,46.836z"></path>
      </svg>
    </a>
  </div>
</footer>
</body>

<script>
  var menu_button = document.getElementById("hamburger-menu");
  var modal = document.getElementById("modal");

  menu_button.addEventListener("click", () => {
    if (modal) {
      modal.style.display = "block";
    } else {
      console.error("Modal element not found.");
    }
  });

  var close_button = document.getElementById("modal-x");

  close_button.addEventListener("click", () => {
    if (modal) {
      modal.style.display = "none";
    } else {
      console.error("Modal element not found.");
    }
  });
</script>
</html>

app/views/payments/_new.html.erb
<%= form_tag payments_path do %>
  <div class="stripe-form">
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>

    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="A month's subscription"
      data-amount="500"
      data-locale="auto">
    </script>
  </div>
<% end %>

app/views/pricing/index.html.erb
<div class="row pricing-content">
  <section class="pricing-description">
    <h1>Pricing options</h1>
    <div>
      <h2>Starter Plan - Get Your Idea Online:</h2>
      <p>
        Launch your online presence with our Starter Plan, ideal for individuals and small businesses
        seeking a professional website or online store. With
        responsive customer support and a user-friendly platform, you'll have the tools you need to get your
        ideas online quickly and affordably
      </p>
    </div>

    <div>
      <h2>Business Plan - Grow Your Online Presence:</h2>
      <p>
        Amplify your online growth with our Business Plan, tailored for
        businesses and entrepreneurs who want advanced features and scalability. Unlock
        powerful tools such as SEO optimization, email marketing integrations, and enhanced
        analytics to attract more customers and drive sales. With priority support and expert guidance,
        you'll have the resources and support necessary to expand your online presence and maximize your success
      </p>
    </div>

    <div>
      <h2>Enterprise Plan - Custom Solutions for Your Business:</h2>
      <p>
        Elevate your online business with our Enterprise Plan, designed for larger organizations and ambitious
        projects. Benefit from fully customizable solutions, dedicated account management, and enterprise-grade
        security features tailored to your business needs. Our team of experts will collaborate closely with you
        to develop customized strategies and solutions that drive growth and innovation, helping you stay ahead
        of
        the competition
      </p>
    </div>
  </section>
</div>

app/views/projects/index.html.erb
<h1>Projects page</h1>

app/views/skills/index.html.erb
<div class="skills-content">
  <h2>Skills</h2>

  <p>
    Here is a list of the skills, I have been using through my career as a software developer
    and I have been polishing through many different projects.
  </p>

  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('ruby.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>Ruby</strong>
      <br>
      Ruby is an interpreted, high-level, general-purpose programming language. It was designed with
      an emphasis on programming productivity and simplicity. In Ruby, everything is an object, including primitive
      data types. It was developed in the mid-1990s by Yukihiro "Matz" Matsumoto in Japan.
    </div>
  </div>

  <div class="language-content right">
    <div class="language-img-content">
      <img src="<%= image_path('html.svg') %>" alt="html img">
    </div>
    <div class="language-description">
      <strong>HTML</strong>
      <br>
      The HyperText Markup Language, or HTML, is the standard markup language for documents designed to be displayed in
      a web browser. HTML describes the structure of a web page semantically and contains the building blocks of a web
      page.
    </div>
  </div>

  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('css-3.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>CSS3</strong>
      <br>
      Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation
      of a document written in a markup language such as HTML. CSS is a cornerstone technology of the World Wide Web.
    </div>
  </div>

  <div class="language-content right">
    <div class="language-img-content">
      <img src="<%= image_path('javascript.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>Javascript</strong>
      <br>
      JavaScript is a programming language that is one of the core technologies of the World
      Wide Web. All major web browsers have a dedicated engine to execute Javascript code on users' devices.
    </div>
  </div>

  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('sql.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>SQL</strong>
      <br>
      Structured Query Language is a standardized programming language that is used to manage relational
      databases and perform various operations on the data in them.
    </div>
  </div>
</div>

app/views/technologies/index.html.erb
<div class="skills-content">
  <h2>Technologies</h2>

  <p>
    Here is a list of the thechnologies I have experience through my career as a software developer
    and I have been polishing through many different projects.
  </p>

  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('ruby.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>Ruby</strong>
      <br>
      Ruby is an interpreted, high-level, general-purpose programming language. It was designed with
      an emphasis on programming productivity and simplicity. In Ruby, everything is an object, including primitive
      data types. It was developed in the mid-1990s by Yukihiro "Matz" Matsumoto in Japan.
    </div>
  </div>

  <div class="language-content right">
    <div class="language-img-content">
      <img src="<%= image_path('javascript.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>Javascript</strong>
      <br>
      JavaScript is a programming language that is one of the core technologies of the World
      Wide Web. All major web browsers have a dedicated engine to execute Javascript code on users' devices.
    </div>
  </div>

  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('sql.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>SQL</strong>
      <br>
      Structured Query Language is a standardized programming language that is used to manage relational
      databases and perform various operations on the data in them.
    </div>
  </div>

  <div class="language-content right">
    <div class="language-img-content">
      <img src="<%= image_path('css-3.svg') %>" alt="img">
    </div>
    <div class="language-description">
      <strong>CSS3</strong>
      <br>
      Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation
      of a document written in a markup language such as HTML. CSS is a cornerstone technology of the World Wide Web.
    </div>
  </div>
  
  <div class="language-content">
    <div class="language-img-content">
      <img src="<%= image_path('html.svg') %>" alt="html img">
    </div>
    <div class="language-description">
      <strong>HTML</strong>
      <br>
      The HyperText Markup Language, or HTML, is the standard markup language for documents designed to be displayed in
      a web browser. HTML describes the structure of a web page semantically and contains the building blocks of a web
      page.
    </div>
  </div>
</div>